### PR TITLE
Tabs and Private Tabs support

### PR DESCRIPTION
**Pull request by iyttor**

### CODE REVIEW

**Comment by iyttor** [comment]
newTab({privateTab}) opens a new Tab
init({privateTab}) returns a new Tab

Private Tab is allowed only in headless mode
maxTabs parameter added to the constructor. default is Infinity

**Comment by iyttor** [comment]
the syntex changed a bit for an activity is done only through a tab

const HeadlessChrome = new HeadlessChrome()
const tabA = await HeadlessChrome.init({privateTab: true})
await tabA.goTo('http://www.google.com')

**Comment by LucianoGanga** [comment]
Hi @iyttor ! 

Great feature! 
I see anyway that the test failed because the browser.goTo method seems to be missing. Is it possible that this works with the previous examples? 

Cheers!
Luciano

**Comment by LucianoGanga** [comment]
I can't see the diff because it seems like you used different indentation. It has 2 spaces per indent, and without tabs. For this project I used "standard js" (I can fix that for you after I merge the PR, but it will be good if you tell me shortly what main changes you did.

**Comment by gr2m** [comment]
@LucianoGanga you should have push access to the fork (it’s the default setting now). There is also a secret flag that ignores all whitespace changes, just add `?w=1` to the files tab URL:
https://github.com/LucianoGanga/simple-headless-chrome/pull/40/files?w=1

But I also don’t know what exactly happened there, I’d try to fix this before merging

**Comment by iyttor** [comment]
- **added support to the current syntax:**
const browser = new HeadlessChrome()
browser.init()
browser.goTo(....)
browser.close()
browser.close(true)

- **there is also support to tabs syntax:**
const browser = new HeadlessChrome()
const tabA = browser.init({privateTab=false})
const tabB = browser.newTab({privateTab=true})
await tabA.goTo(...)
await tabB.goTo(..)
await browser.closeTab(tabA.getId())
await browser.closeTab(tabB.getId())
browser.exit()

- **for clarification - the default browser uses the same tab as the tabA - so for example:**
const browser = new HeadlessChrome()
const tab = browser.init()
tab.goTo(....)
browser.closeTab(tab.getId())
_------browser.goTo(...) -----won't work_

_I don't really like the easy way i supported the default syntax, by assigning a new tab object to the main HeadlessChrome class. But it works._

- also added tabs test to the tests folder
- tried to fix identaion with no luck...

**Comment by iyttor** [comment]
@LucianoGanga it seems you can merge it now safely.
I included Chrome flags - Pull #41, and tests are also working fine with the default syntax

there is some problem with the spaces though, so you need to resolve it.

**Comment by LucianoGanga** [comment]
Hi! 

I just made some simple corrections and everything looks without conflict. 

Anyway, the test still fails (don't know why), but I'll merge this PR this weekend and debug the issue so we can release this in the NPM package :) 

This is an excellent work @iyttor !! I love this! 

@gr2m thanks for the tip with the `?w=1`, I didn't know that! 

I'll let you know when it's done. 

Sorry for taking so long, but I had a surgery and I'm working only part time. 

Cheers!
Lucho

**Comment by gr2m** [comment]
Get well soon!

**Comment by LucianoGanga** [comment]
Thanks! I'm checking this out right now.. I merged it with the test failing but I won't publish in NPM until it's solved. 

I'll let you know in this thread when I finish solving the issues.

Thanks for your help!

**Comment by iyttor** [comment]
@LucianoGanga Be well!

**Comment by fusionx1** [comment]
This is a great merge. Did some test and I'm getting an error: 

`/Users/fusionx1/Projects/headless-chrome/my-headless-chrome/index.js:12
const tabA = browser.init({privateTab=false})
                           ^^^^^^^^^^^^^^^^
SyntaxError: Invalid shorthand property initializer
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)`

**Comment by fusionx1** [comment]
Followed the steps above.

**Comment by LucianoGanga** [comment]
Hi @fusionx1 ! I'm working on the final release of these features today. The repository is now with some errors, but they're not published in NPM yet. 

This will be continued in the PR #45 

Thanks!

**Pull request merged**
