### PR TITLE
add auto-generated docs for methods

### PR DESCRIPTION
**Pull request by gr2m**
hey this is just a suggestion, I used [documentation.js](http://documentation.js.org/) to dynamically replace the `Methods` section in the README with API docs generated out of the `lib/actions.js` file.

It also changed other parts of the README unfortunately I don’t think there is a way to disable it. But I think once we merge it in it shouldn’t make changes outside of the Methods section again.

We could add an `npm run documentation` task that updates the README. If you use the `npm version` command to generate the tags and version commits, we can run it on `preversion`.

What you think?

### CODE REVIEW

**Comment by LucianoGanga** [comment]
You rock @gr2m ! Thank you for this :D 

How do we add it on the preversion? Just as a script call in tha package.json? 

Oh, BTW... The documentation module is in the dependencies object, but shouldn't it be in the dev-dependencies object? 

Cheers!
Luciano

**Comment by gr2m** [comment]
> The documentation module is in the dependencies object, but shouldn't it be in the dev-dependencies object?

Yes I’m sorry this wasn’t ready for merging yet, I should have made it clear. I’ll send a follow up PR right away :)

**Comment by LucianoGanga** [comment]
Don't worry! I merged it anyway but I didn't build the new npm version, so It didn't affect anybody :)

**Comment by gr2m** [comment]
here is the follow up: https://github.com/LucianoGanga/simple-headless-chrome/issues/27

**Pull request merged**
