### PR TITLE
Support previous versions of Node up until 4

### LINKED ISSUE #31: Make `simple-headless-chrome` run in node LTS
hey @LucianoGanga I wonder if you would be okay to change the code of the `lib/*` files so that the library would run in older node versions? We can still use async/await in tests. And I don’t think that the code become less readable. 

We have a project where we would love to use `simple-headless-chrome` but can’t right now because we can’t upgrade the node versions anytime soon :( I’d be happy to send a PR myself. If you are unsure, I can start so you can see some of the diff. Let me know :)

### PR DESCRIPTION
**Pull request by lewisf**
Fixes #31 

Add babel/babel-polyfill to compile src/ so that simple headless chrome can be consumed by other Node versions as early as Node 4.

I made corresponding changes to package.json to make sure the dev flow is still solid using `yarn watch` and `yarn test`. Also updated `engines` to say `node >= 4`

### CODE REVIEW

**Comment by LucianoGanga** [comment]
Hello @lewisf ! 
Thanks for your contribution! This is great!!! 😄 

I'll merge this PR asap. I'll let you know when it's ready. 

Cheers!
Lucho

**Comment by LucianoGanga** [comment]
@lewisf, is it possible to do that the module chooses whether to use the files built in /lib or the files in /src, depending on the Node version being used? 

Because I'm thinking, for debugging purposes, if you're running node 8.*, it's useful to have everything without the magic of Babel. 

Thanks!
Lucho

**Comment by lewisf** [comment]
@LucianoGanga, I don't think so :( at least not that I'm aware. it's probably possible to publish two different packages: one for node 8 and one compatible back to node 4 (where this one gets prebuilt), but I haven't seen that before.

**Comment by LucianoGanga** [comment]
Thanks! I'll think on something. :) 

Cheers!
Lucho

**Pull request merged**
