### PR TITLE
Little fixes so tests are passing

### PR DESCRIPTION
**Pull request by iyttor**
Everything else is updated.

### CODE REVIEW

**Comment by iyttor** [comment]
To my opinion there is a need to consider changing the syntax to the tabs point of view - like the syntax i proposed. The point is that the main Headless class only creates a browser, though the browsing and evaluation is done only through a tab like in a real browser. So init() will return a tab to take care of the activity, and browser will take care of the management.

By the code, In order to support the default old syntax I had to Object.assign() one tab to the main class. It seems to me that the code would be much safer without the forced assignment of a tab with all its CDP actions/handlers etc. to the main class.

**Comment by LucianoGanga** [comment]
Hi @iyttor ! Thanks! I was working on this yesterday too, but I'm having some troubles with a new test that I was trying to create so I didn't pushed my changes. 

About your opinion, it makes a lot of sense, but besides deprecating methods that other people may be using now, we add a new layer to the person that uses the module (we force them to use tabs, even when the most used scenario is with only a single tab). 

My idea is that when you open a web browser, you don't worry about the first tab; you navigate directly. Then, if you need a new one, you just open it. 

I'll be working on this today too, and I'll let you know here my proposal. 

Thanks!
Lucho

**Comment by LucianoGanga** [comment]
Oh, about the line
`const { targetId } = await Target.createTarget(params)`

I had to move it the way I pushed to the repo yesterday because if you set the const inside the "try", you can only use it in that context, and you can't get access to it inside the "catch".

**Comment by iyttor** [comment]
@LucianoGanga i agree that the regular use is only one tab, so we can still
support it that way:
const HeadlessChrome = require ('headless-chrome')
const chrome = new HeadlessChrome()
const browser = chrome.init()

Though it won't support the old syntax..


In regards to the code fix - my mistake. The problem is that it works only
that way (there is something wierd with how the chrome protocol takea care
of the id variable). I think that changing it from const { targetId } to
var {targetId}, should solve the scoping problem.

בתאריך 30 ביולי 2017 17:55,‏ "Luciano" <notifications@github.com> כתב:

**Comment by LucianoGanga** [comment]
> In regards to the code fix - my mistake. The problem is that it works only
that way (there is something wierd with how the chrome protocol takea care
of the id variable). I think that changing it from const { targetId } to
var {targetId}, should solve the scoping problem.

I see... I was going crazy after I made that change and everything broke suddenly haha. 
I'll try to find out what's not allowing us to do it that way. If I can't, I'll do what you say, and use `var`. 

Thanks!

**Comment by LucianoGanga** [comment]
@iyttor I have one question. What's the new method "exit()" for? And what's the difference with the "close()" method? 

BTW... I'm adding some release notes with information about the new syntax. We will keep the support of the old syntax during the version 3.x.x but from v4.0.0, we will move that to the syntax you proposed before. 

All this changes will be pushed today :)

**Comment by iyttor** [comment]
close({tabid}) is used for closing a tab,
exit() is usedfor closing the browser

Currently, close() is used for closing the default tab and close(true) is
used for closing the browser. i think we should consider cancelling the
close(true), and move to exit() instead

בתאריך 30 ביולי 2017 19:23,‏ "Luciano" <notifications@github.com> כתב:

**Comment by iyttor** [comment]
Great!
Good job

בתאריך 30 ביולי 2017 19:37,‏ "Issar Tzachor" <iyttor@gmail.com> כתב:

**Comment by LucianoGanga** [comment]
I made a lot of changes to split in different files the Tab class and the Browser class, but I can't make it work yet :( 

I get this errors: 

```
(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'Network' of undefined
(node:3400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Missing or invalid 'targetId' parameter
(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'Emulation' of undefined
``` 

You can see the changes here:
https://github.com/LucianoGanga/simple-headless-chrome/tree/beta

I'll continue with this now, but if you test it and it works please let me know (that would mean that it's an issue with my Chrome and not with the code)

Thanks!
Lucho

**Comment by LucianoGanga** [comment]
Just reporting here...

The issue happens when the instance is not in headless mode (even with non private tabs).

I'll check the documentation of the CDP protocol to see if there's another way to do this, and keep support for non-headless instances.

**Comment by iyttor** [comment]
It worked well before - in both headless and non-headless modes..

בתאריך 30 ביולי 2017 23:14,‏ "Luciano" <notifications@github.com> כתב:

**Comment by LucianoGanga** [comment]
Found it! And solved it too (I think)

Were you testing this on windows? 

The problem is that when you do 
```js
    if (process.platform === 'win32') {
      client = await CDP({ host, port, remote })
    } else {
      client = await CDP({ target: `ws://${host}:${port}/devtools/browser` })
    }
```

in a Mac, you can't access to all the browser methods. If I remove that and only do this: 

```js
      client = await CDP({ host, port, remote })
```
it works like a charm. 

I'll be putting all together now and publishing version 3.3.0, with backwards compatibility, and then publish version 4.0.0 breaking the compatibility, but simplifying code.

**Comment by LucianoGanga** [comment]
Done! 
- Published v3.3.1 including tabs support + deprecation warnings
- Published v.4.0.0 including tabs support but with the syntax that you recommended. 

Comments are more than welcome :) 

Thanks for everything! 
Lucho

**Comment by fusionx1** [comment]
wow great work Luciano and iyttor. I will help test.

**Comment by LucianoGanga** [comment]
Thanks @fusionx1 ! 

If when you're testing you make some code that can be useful as an example, feel free to upload it into the "/examples" directory :) 

It may help others. 

Cheers!
Lucho

**Comment by fusionx1** [comment]
Are these still applicable?

added support to the current syntax:
const browser = new HeadlessChrome()
browser.init()
browser.goTo(....)
browser.close()
browser.close(true)

there is also support to tabs syntax:
const browser = new HeadlessChrome()
const tabA = browser.init({privateTab=false})
const tabB = browser.newTab({privateTab=true})
await tabA.goTo(...)
await tabB.goTo(..)
await browser.closeTab(tabA.getId())
await browser.closeTab(tabB.getId())
browser.exit()

for clarification - the default browser uses the same tab as the tabA - so for example:
const browser = new HeadlessChrome()
const tab = browser.init()
tab.goTo(....)
browser.closeTab(tab.getId())

**Comment by LucianoGanga** [comment]
Not in version >= 4.0.0. 

The version 3.3.0 is only a "previous step" for migration to v4.0.0 for those who already have tools that depend on simple-headless-chrome module. 

If you're building something new, I'd recommend you to use the new syntax here: 
https://github.com/LucianoGanga/simple-headless-chrome/blob/master/release-notes.md#release-notes-for-version-400

Let me know if you need some help with this :) 

Thanks!
Lucho

**Comment by fusionx1** [comment]
Hi Luciano,

Thank you for the info. Im trying to close a tab but the earlier command is no longer working.

  const mainTab = await browser.newTab({
    privateTab: false // Optional. Defaults to false
  })

  const secondTab = await browser.newTab({
    privateTab: false // Optional. Defaults to false
  })

  await mainTab.goTo('http://site.com')
  await mainTab.fill('#edit-name', 'xxxxx')
  // Type in an element
  await mainTab.fill('#edit-pass', 'xxxxxxx')
  await mainTab.click('#edit-submit')
  await mainTab.log('Click login')
  await mainTab.log('Wait 5 seconds')
  await mainTab.wait(3000)
  await mainTab.saveScreenshot('./onelogin.png')
  // Navigate to a URL
  await browser.closeTab(mainTab.getId())
  await secondTab.goTo('http://site.com')

**Comment by LucianoGanga** [comment]
Try using this instead
```js
await mainTab.close() 
```

Tip: If you write your code between this three quotes like this -> `, you get the special format for code.

**Comment by fusionx1** [comment]
If im trying to close it, im getting an error below:

(node:43403) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: There was a problem closing target/tab. Invalid parameters (browserContextId: string value expected)
(node:43403) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by LucianoGanga** [comment]
@fusionx1 try now, version 4.0.3. 

There was a bug. I'm sorry! 

BTW, the syntax is the one I wrote in the last comment. I hope this helps!

Cheers, 
Lucho

**Comment by iyttor** [comment]
Great work!
I fixed private tabs close() in pull #46

**Pull request closed without merging**
